// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSuFEair5oWrQS5vdc2OCF2jN-lc7SuyE',
    appId: '1:252150545405:web:3f223cc833f7789038f794',
    messagingSenderId: '252150545405',
    projectId: 'chatroom-2ec8d',
    authDomain: 'chatroom-2ec8d.firebaseapp.com',
    storageBucket: 'chatroom-2ec8d.appspot.com',
    measurementId: 'G-NCMJETB0L7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYqAWMCe9PZzC4gxrEGqwHwq8wpvjkxCk',
    appId: '1:252150545405:android:4742463045536b6038f794',
    messagingSenderId: '252150545405',
    projectId: 'chatroom-2ec8d',
    storageBucket: 'chatroom-2ec8d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxVEjOKqJg7Lw57Tjyvo4ybKYvZEN4BDc',
    appId: '1:252150545405:ios:551a646cb01a8ecb38f794',
    messagingSenderId: '252150545405',
    projectId: 'chatroom-2ec8d',
    storageBucket: 'chatroom-2ec8d.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxVEjOKqJg7Lw57Tjyvo4ybKYvZEN4BDc',
    appId: '1:252150545405:ios:a9f51d8e267579b138f794',
    messagingSenderId: '252150545405',
    projectId: 'chatroom-2ec8d',
    storageBucket: 'chatroom-2ec8d.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
